from __future__ import annotations

"""Public import surface for the Valiance types library."""

from valiance.types.builders import (
    Atomic,
    C,
    CSTC,
    Exact,
    Fn,
    I,
    N,
    Never,
    NoneType,
    Overloads,
    Result,
    Some,
    Tagged,
    Tup,
    U,
    V,
    normalize,
    optional,
    same,
    show,
)
from valiance.types.model import (
    AppliedOverload,
    Coll,
    Context,
    Kind,
    Overload,
    ResolvedOverload,
    Specificity,
    StackApplication,
    Type,
)
from valiance.types.relations import (
    _combine_all,
    _match_specificity,
    _solve,
    _substitute,
    apply_overload,
    apply_overload_to_stack,
    assignable,
    compatible,
    merge_stacks,
    merge_types,
    resolve_overload_result,
)

__all__ = [
    "AppliedOverload",
    "Atomic",
    "C",
    "CSTC",
    "Coll",
    "Context",
    "Exact",
    "Fn",
    "I",
    "Kind",
    "N",
    "Never",
    "NoneType",
    "Overload",
    "Overloads",
    "ResolvedOverload",
    "Result",
    "Some",
    "Specificity",
    "StackApplication",
    "Tagged",
    "Tup",
    "Type",
    "U",
    "V",
    "_combine_all",
    "_match_specificity",
    "_solve",
    "_substitute",
    "apply_overload",
    "apply_overload_to_stack",
    "assignable",
    "compatible",
    "merge_stacks",
    "merge_types",
    "normalize",
    "optional",
    "resolve_overload_result",
    "same",
    "show",
]
