"""Source rewriting, doc-comment extraction, and reference generation."""

from __future__ import annotations

import html
import re
from collections.abc import Iterable, Sequence
from dataclasses import dataclass, fields, is_dataclass
from pathlib import Path
from typing import Any

from valiance.asts import ASTNode, DefineNode, FunctionParam
from valiance.parsing import parse
from valiance.parsing.lexer import Token, TokenKind, lex
from valiance.vtypes import show

DOC_COMMENT_PREFIX = "#??"
DEFAULT_REFERENCE_FILENAME = "reference.html"
_EXCLUDED_PROJECT_DIRS = frozenset(
    {".git", ".vln", "bin", "build", "dist", "__pycache__"}
)
_DOC_FIELD_RE = re.compile(r"^@(param|typeparam)\s+(\S+)(?:\s+(.*))?$")
_DOC_RETURNS_RE = re.compile(r"^@returns?(?:\s+(.*))?$")


@dataclass(frozen=True, slots=True)
class DocField:
    """One named field in a Valiance doc comment."""

    name: str
    description: str


@dataclass(frozen=True, slots=True)
class ParsedDocstring:
    """Structured contents of one contiguous ``#??`` block."""

    description: tuple[str, ...] = ()
    params: tuple[DocField, ...] = ()
    type_params: tuple[DocField, ...] = ()
    returns: str | None = None
    extra_fields: tuple[str, ...] = ()


@dataclass(frozen=True, slots=True)
class DefinitionReference:
    """One documented ``define`` declaration."""

    name: str
    signature: str
    source_path: str
    line: int
    docstring: ParsedDocstring


@dataclass(frozen=True, slots=True)
class _FormatFrame:
    kind: str
    original_indent: int


def project_source_files(root: Path) -> tuple[Path, ...]:
    """Return Valiance source files belonging to a project.

    Generated bytecode, installed dependencies, VCS metadata, and common build
    directories are deliberately excluded. Project tests remain included: they
    are source code and should be tidied consistently with the rest of a project.
    """

    resolved_root = root.resolve()
    paths = []
    for path in resolved_root.rglob("*.vlnc"):
        relative = path.relative_to(resolved_root)
        if any(part in _EXCLUDED_PROJECT_DIRS for part in relative.parts[:-1]):
            continue
        if path.is_file():
            paths.append(path)
    return tuple(sorted(paths, key=lambda item: item.as_posix().casefold()))


def add_missing_docstrings(source: str) -> str:
    """Insert a structured doc-comment stub before every undocumented define."""

    program = parse(source)
    definitions = sorted(
        (node for node in _walk_ast(program) if isinstance(node, DefineNode)),
        key=lambda node: node.location.offset if node.location is not None else -1,
        reverse=True,
    )
    if not definitions:
        return source

    lines = source.splitlines(keepends=True)
    line_starts = _line_starts(source)
    rendered = source
    for definition in definitions:
        if definition.location is None:
            continue
        line_index = definition.location.line - 1
        if _doc_block_before(lines, line_index) is not None:
            continue
        insertion_line_index = line_index
        while (
            insertion_line_index > 0
            and lines[insertion_line_index - 1].lstrip().startswith("@")
        ):
            insertion_line_index -= 1
        line = (
            lines[insertion_line_index]
            if insertion_line_index < len(lines)
            else ""
        )
        indent = line[: len(line) - len(line.lstrip(" \t"))]
        stub = _docstring_stub(definition, indent)
        offset = line_starts[insertion_line_index]
        rendered = rendered[:offset] + stub + rendered[offset:]
    return rendered


def extract_documented_defines(
    source: str,
    *,
    source_path: str = "<source>",
) -> tuple[DefinitionReference, ...]:
    """Extract documented definitions from one parsed source file."""

    program = parse(source)
    lines = source.splitlines()
    definitions: list[DefinitionReference] = []
    for node in _walk_ast(program):
        if not isinstance(node, DefineNode) or node.location is None:
            continue
        block = _doc_block_before(lines, node.location.line - 1)
        if block is None:
            continue
        definitions.append(
            DefinitionReference(
                name=str(node.name),
                signature=_definition_signature(node),
                source_path=source_path,
                line=node.location.line,
                docstring=parse_docstring(block),
            )
        )
    definitions.sort(key=lambda item: (item.line, item.name))
    return tuple(definitions)


def parse_docstring(lines: Sequence[str]) -> ParsedDocstring:
    """Parse the contents of a contiguous ``#??`` comment block."""

    description: list[str] = []
    params: list[DocField] = []
    type_params: list[DocField] = []
    returns: str | None = None
    extras: list[str] = []

    for raw_line in lines:
        content = raw_line.lstrip()[len(DOC_COMMENT_PREFIX) :]
        if content.startswith(" "):
            content = content[1:]
        field_match = _DOC_FIELD_RE.match(content)
        if field_match is not None:
            kind, name, field_description = field_match.groups()
            field = DocField(name, field_description or "")
            if kind == "param":
                params.append(field)
            else:
                type_params.append(field)
            continue
        returns_match = _DOC_RETURNS_RE.match(content)
        if returns_match is not None:
            returns = returns_match.group(1) or ""
            continue
        if content.startswith("@"):
            extras.append(content)
            continue
        description.append(content)

    while description and not description[-1]:
        description.pop()
    return ParsedDocstring(
        tuple(description),
        tuple(params),
        tuple(type_params),
        returns,
        tuple(extras),
    )


def render_html_reference(
    definitions: Sequence[DefinitionReference],
    *,
    title: str = "Valiance Reference",
) -> str:
    """Render a self-contained HTML reference from documented definitions."""

    grouped: dict[str, list[DefinitionReference]] = {}
    for definition in definitions:
        grouped.setdefault(definition.source_path, []).append(definition)

    navigation: list[str] = []
    sections: list[str] = []
    used_anchors: set[str] = set()
    for source_path in sorted(grouped, key=str.casefold):
        source_anchor = _unique_anchor(f"file-{source_path}", used_anchors)
        navigation.append(
            f'<li><a href="#{html.escape(source_anchor)}">'
            f"{html.escape(source_path)}</a></li>"
        )
        cards = []
        for definition in grouped[source_path]:
            anchor = _unique_anchor(
                f"{source_path}-{definition.name}-{definition.line}", used_anchors
            )
            cards.append(_definition_card(definition, anchor))
        sections.append(
            "\n".join(
                (
                    f'<section class="source-file" id="{html.escape(source_anchor)}">',
                    f"  <h2>{html.escape(source_path)}</h2>",
                    *cards,
                    "</section>",
                )
            )
        )

    if not sections:
        sections.append(
            '<p class="empty">No <code>#??</code> documentation comments '
            "were found.</p>"
        )

    nav_html = ""
    if navigation:
        nav_html = "\n".join(
            (
                '<nav aria-label="Source files">',
                "  <h2>Files</h2>",
                "  <ul>",
                *(f"    {item}" for item in navigation),
                "  </ul>",
                "</nav>",
            )
        )

    return "\n".join(
        (
            "<!doctype html>",
            '<html lang="en">',
            "<head>",
            '  <meta charset="utf-8">',
            '  <meta name="viewport" content="width=device-width, initial-scale=1">',
            f"  <title>{html.escape(title)}</title>",
            "  <style>",
            _REFERENCE_CSS,
            "  </style>",
            "</head>",
            "<body>",
            "  <header>",
            f"    <h1>{html.escape(title)}</h1>",
            "    <p>Generated from Valiance <code>#??</code> documentation "
            "comments.</p>",
            "  </header>",
            '  <div class="layout">',
            f"    {nav_html}" if nav_html else "",
            "    <main>",
            *(f"      {line}" for section in sections for line in section.splitlines()),
            "    </main>",
            "  </div>",
            "</body>",
            "</html>",
            "",
        )
    )


def format_source(source: str, *, indent_width: int = 2) -> str:
    """Normalize leading indentation while preserving source text otherwise.

    Valiance indentation is not semantic, so the formatter deliberately avoids
    changing expression spacing or line breaks. It only derives block depth from
    multiline ``=>`` constructs, branch markers, and ``end`` tokens.
    """

    if indent_width < 0:
        raise ValueError("indent_width must not be negative")
    tokens = lex(source)
    tokens_by_line: dict[int, list[Token]] = {}
    for token in tokens:
        if token.kind not in {
            TokenKind.WHITESPACE,
            TokenKind.NEWLINE,
            TokenKind.EOF,
        }:
            tokens_by_line.setdefault(token.line, []).append(token)

    string_continuation_lines = _string_continuation_lines(tokens)
    frames: list[_FormatFrame] = []
    rendered_lines: list[str] = []

    for line_number, raw_line in enumerate(source.splitlines(keepends=True), start=1):
        content, ending = _split_line_ending(raw_line)
        if line_number in string_continuation_lines:
            rendered_lines.append(raw_line)
            continue
        stripped = content.lstrip(" \t")
        if not stripped:
            rendered_lines.append(ending)
            continue

        original_indent = _indent_columns(content[: len(content) - len(stripped)])
        line_tokens = tokens_by_line.get(line_number, [])
        identifiers = [
            token.value for token in line_tokens if token.kind is TokenKind.IDENT
        ]
        first_identifier = identifiers[0] if identifiers else None
        ends_arrow = bool(
            line_tokens and line_tokens[-1].kind is TokenKind.FAT_ARROW
        )

        if frames and frames[-1].kind == "case":
            if stripped.startswith("end") or _looks_like_match_case_start(line_tokens):
                frames.pop()

        if first_identifier == "end":
            if frames and frames[-1].kind == "case":
                frames.pop()
            if frames:
                frames.pop()
            depth = len(frames)
            rendered_lines.append(" " * (depth * indent_width) + stripped + ending)
            continue

        branch_target = None
        if first_identifier == "else":
            branch_target = _last_frame(frames, {"if", "assert"})
        elif first_identifier == "handle":
            branch_target = _last_frame(frames, {"try"})

        if branch_target is not None:
            frames[:] = frames[: branch_target + 1]
            depth = branch_target
        else:
            depth = len(frames)

        rendered_lines.append(" " * (depth * indent_width) + stripped + ending)

        if not ends_arrow or branch_target is not None:
            continue
        if frames and frames[-1].kind == "match":
            frames.append(_FormatFrame("case", original_indent))
            continue
        frames.append(_FormatFrame(_format_frame_kind(identifiers), original_indent))

    return "".join(rendered_lines)


def _walk_ast(value: Any) -> Iterable[ASTNode]:
    """Compute walk AST for source rewriting and generated documentation."""
    if isinstance(value, ASTNode):
        yield value
    if isinstance(value, (str, bytes, int, float, type(None))):
        return
    if isinstance(value, dict):
        children = value.values()
    elif isinstance(value, (tuple, list, set, frozenset)):
        children = value
    elif is_dataclass(value) and type(value).__module__.startswith("valiance.asts"):
        children = (getattr(value, field.name) for field in fields(value))
    else:
        return
    for child in children:
        yield from _walk_ast(child)


def _line_starts(source: str) -> tuple[int, ...]:
    """Compute line starts for source rewriting and generated documentation."""
    starts = [0]
    for index, character in enumerate(source):
        if character == "\n":
            starts.append(index + 1)
    return tuple(starts)


def _doc_block_before(
    lines: Sequence[str],
    definition_line_index: int,
) -> tuple[str, ...] | None:
    """Compute doc block before for source rewriting and generated documentation."""
    index = definition_line_index - 1
    while index >= 0 and lines[index].lstrip().startswith("@"):
        index -= 1
    if index < 0 or not lines[index].lstrip().startswith(DOC_COMMENT_PREFIX):
        return None
    end = index + 1
    while index >= 0 and lines[index].lstrip().startswith(DOC_COMMENT_PREFIX):
        index -= 1
    return tuple(lines[index + 1 : end])


def _docstring_stub(definition: DefineNode, indent: str) -> str:
    """Compute docstring stub for source rewriting and generated documentation."""
    lines = [f"{indent}{DOC_COMMENT_PREFIX} TODO: Describe `{definition.name}`."]
    field_lines: list[str] = []
    for generic in definition.generics:
        field_lines.append(
            f"{indent}{DOC_COMMENT_PREFIX} @typeparam {generic} "
            f"TODO: Describe `{generic}`."
        )
    params = definition.function.params
    if params is not None:
        for index, param in enumerate(params):
            name = str(param.name) if param.name is not None else f"_{index}"
            field_lines.append(
                f"{indent}{DOC_COMMENT_PREFIX} @param {name} "
                f"TODO: Describe `{name}`."
            )
    returns = definition.function.returns
    if returns:
        field_lines.append(
            f"{indent}{DOC_COMMENT_PREFIX} @returns "
            "TODO: Describe the returned stack value(s)."
        )
    if field_lines:
        lines.append(f"{indent}{DOC_COMMENT_PREFIX}")
        lines.extend(field_lines)
    return "\n".join(lines) + "\n"


def _definition_signature(definition: DefineNode) -> str:
    """Build the signature for definition for source rewriting and generated documentation."""
    parts: list[str] = []
    if definition.visibility is not None:
        parts.append(str(definition.visibility))
    if definition.is_multi:
        parts.append("multi")
    parts.append("define")
    if definition.generics:
        generics = ", ".join(str(generic) for generic in definition.generics)
        parts[-1] += f"[{generics}]"
    if definition.attached_tag is not None:
        parts.append(str(definition.attached_tag))
    parts.append(str(definition.name))

    params = definition.function.params
    if params is not None:
        rendered_params = ", ".join(
            _parameter_signature(param) for param in params
        )
        parts[-1] += f"({rendered_params})"
    returns = definition.function.returns
    if returns is not None:
        rendered_returns = ", ".join(show(item) for item in returns)
        parts.append(f"-> {rendered_returns}" if rendered_returns else "-> ()")
    return " ".join(parts)


def _parameter_signature(param: FunctionParam) -> str:
    """Build the signature for parameter for source rewriting and generated documentation."""
    name = "" if param.name is None else str(param.name)
    typ = "?" if param.typ is None else show(param.typ)
    label = f"{name}: {typ}" if name else f":{typ}"
    if param.default:
        label += " = …"
    return label


def _definition_card(definition: DefinitionReference, anchor: str) -> str:
    """Compute definition card for source rewriting and generated documentation."""
    doc = definition.docstring
    body: list[str] = [
        f'<article class="definition" id="{html.escape(anchor)}">',
        f"  <h3>{html.escape(definition.name)}</h3>",
        f"  <pre><code>{html.escape(definition.signature)}</code></pre>",
        f'  <p class="location">Line {definition.line}</p>',
    ]
    body.extend(f"  {line}" for line in _description_html(doc.description))
    fields_html = _fields_html(doc)
    body.extend(f"  {line}" for line in fields_html)
    body.append("</article>")
    return "\n".join(body)


def _description_html(lines: Sequence[str]) -> tuple[str, ...]:
    """Compute description html for source rewriting and generated documentation."""
    paragraphs: list[str] = []
    current: list[str] = []
    for line in lines:
        if line:
            current.append(line)
            continue
        if current:
            paragraphs.append(" ".join(current))
            current = []
    if current:
        paragraphs.append(" ".join(current))
    return tuple(f"<p>{_inline_doc_html(paragraph)}</p>" for paragraph in paragraphs)


def _fields_html(doc: ParsedDocstring) -> tuple[str, ...]:
    """Compute fields html for source rewriting and generated documentation."""
    rows: list[tuple[str, str, str]] = []
    rows.extend(
        ("Type parameter", field.name, field.description)
        for field in doc.type_params
    )
    rows.extend(("Parameter", field.name, field.description) for field in doc.params)
    if doc.returns is not None:
        rows.append(("Returns", "", doc.returns))
    rows.extend(("Other", "", field) for field in doc.extra_fields)
    if not rows:
        return ()
    rendered = ['<dl class="fields">']
    for kind, name, description in rows:
        label = f"{kind} <code>{html.escape(name)}</code>" if name else kind
        rendered.append(f"  <dt>{label}</dt>")
        rendered.append(f"  <dd>{_inline_doc_html(description)}</dd>")
    rendered.append("</dl>")
    return tuple(rendered)


def _inline_doc_html(value: str) -> str:
    """Compute inline doc html for source rewriting and generated documentation."""
    pieces = re.split(r"(`[^`]+`)", value)
    rendered: list[str] = []
    for piece in pieces:
        if len(piece) >= 2 and piece.startswith("`") and piece.endswith("`"):
            rendered.append(f"<code>{html.escape(piece[1:-1])}</code>")
        else:
            rendered.append(html.escape(piece))
    return "".join(rendered)


def _slug(value: str) -> str:
    """Compute slug for source rewriting and generated documentation."""
    slug = re.sub(r"[^a-z0-9]+", "-", value.casefold()).strip("-")
    return slug or "item"


def _unique_anchor(value: str, used: set[str]) -> str:
    """Compute unique anchor for source rewriting and generated documentation."""
    base = _slug(value)
    anchor = base
    suffix = 2
    while anchor in used:
        anchor = f"{base}-{suffix}"
        suffix += 1
    used.add(anchor)
    return anchor


def _split_line_ending(line: str) -> tuple[str, str]:
    """Split line ending for source rewriting and generated documentation."""
    if line.endswith("\r\n"):
        return line[:-2], "\r\n"
    if line.endswith("\n") or line.endswith("\r"):
        return line[:-1], line[-1]
    return line, ""


def _indent_columns(value: str) -> int:
    """Compute indent columns for source rewriting and generated documentation."""
    return len(value.expandtabs(2))


def _string_continuation_lines(tokens: Sequence[Token]) -> frozenset[int]:
    """Compute string continuation lines for source rewriting and generated documentation."""
    lines: set[int] = set()
    for token in tokens:
        if token.kind is not TokenKind.STRING or token.raw is None:
            continue
        newline_count = token.raw.count("\n")
        lines.update(range(token.line + 1, token.line + newline_count + 1))
    return frozenset(lines)


def _last_frame(frames: Sequence[_FormatFrame], kinds: set[str]) -> int | None:
    """Compute last frame for source rewriting and generated documentation."""
    for index in range(len(frames) - 1, -1, -1):
        if frames[index].kind in kinds:
            return index
    return None


def _format_frame_kind(identifiers: Sequence[str]) -> str:
    """Format frame kind for source rewriting and generated documentation."""
    if "define" in identifiers:
        return "define"
    if "match" in identifiers:
        return "match"
    first = identifiers[0] if identifiers else "block"
    if first in {
        "if",
        "assert",
        "try",
        "while",
        "unfold",
        "foreach",
        "for",
        "fn",
        "object",
        "trait",
        "variant",
        "enum",
        "at",
    }:
        return first
    return "block"


def _looks_like_match_case_start(tokens: Sequence[Token]) -> bool:
    """Return the Boolean result of looks like match case start for source rewriting and generated documentation."""
    if not tokens:
        return False
    first = tokens[0]
    if first.kind is TokenKind.IDENT and first.value in {
        "as",
        "default",
        "if",
        "_",
    }:
        return True
    return first.kind in {
        TokenKind.NUMBER,
        TokenKind.STRING,
        TokenKind.LBRACKET,
    }


_REFERENCE_CSS = """    :root {
      color-scheme: light dark;
      font-family: Inter, ui-sans-serif, system-ui, sans-serif;
      line-height: 1.55;
    }
    body { margin: 0; background: Canvas; color: CanvasText; }
    header { padding: 2rem clamp(1rem, 5vw, 4rem); border-bottom: 1px solid GrayText; }
    header h1 { margin: 0 0 .35rem; }
    header p { margin: 0; color: GrayText; }
    .layout {
      display: grid;
      grid-template-columns: minmax(12rem, 18rem) 1fr;
      gap: 2rem;
      padding: 2rem clamp(1rem, 5vw, 4rem);
    }
    nav { position: sticky; top: 1rem; align-self: start; }
    nav h2 { font-size: 1rem; text-transform: uppercase; letter-spacing: .08em; }
    nav ul { list-style: none; padding: 0; }
    nav li { margin: .5rem 0; }
    a { color: LinkText; }
    main { min-width: 0; }
    .source-file { margin-bottom: 3rem; }
    .definition {
      padding: 1.25rem;
      margin: 1rem 0;
      border: 1px solid GrayText;
      border-radius: .75rem;
    }
    .definition h3 { margin-top: 0; }
    pre {
      overflow-x: auto;
      padding: .8rem;
      border-radius: .5rem;
      background: color-mix(in srgb, CanvasText 8%, Canvas);
    }
    code { font-family: ui-monospace, SFMono-Regular, Consolas, monospace; }
    .location { color: GrayText; font-size: .9rem; }
    .fields { display: grid; grid-template-columns: max-content 1fr; gap: .35rem 1rem; }
    .fields dt { font-weight: 650; }
    .fields dd { margin: 0; }
    .empty { padding: 1rem; border: 1px dashed GrayText; border-radius: .5rem; }
    @media (max-width: 760px) {
      .layout { grid-template-columns: 1fr; }
      nav { position: static; }
    }"""
